#!/usr/bin/env lua
--cubix: well, cubix!

AUTHOR = "Lukas Mendes"
BUILD_DATE = "2015-10-21"
VERSION = "0.3.4"
--[[
    version: major.revision.minor
        major: linear
        revision: odd: unstable
        revision: even: stable
        minor: number of RELEASES necessary to get to this version, not including BUILDS
]]

--installing set_term_color
term.set_term_color = function (c)
    if term.isColor() then
        term.setTextColor(c)
    end
end

local Args = {...} --arguments to shell

os.__boot_flag = true

os.strsplit = function (inputstr, sep)
    if sep == nil then
        sep = "%s"
    end
    if inputstr == nil then
        return ''
    end
    local t={} ; i=1
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
        t[i] = str
        i = i + 1
    end
    return t
end

kflag = {}

for k,v in pairs(Args) do
    if v == 'quiet' then
        kflag.quiet = true
    elseif v == 'nodebug' then
        kflag.nodebug = true
    elseif v == 'splash' then
        kflag.splash = true
    elseif v == 'acpi' then
        kflag.acpi = true
    elseif string.sub(v, 0, 4) == 'init' then
        k = os.strsplit(v, '=')
        kflag.init = k[2]
    elseif string.sub(v, 0, 4) == 'runlevel' then
        k = os.strsplit(v, '=')
        kflag.sRunlevel = k[2]
    end
end

if kflag.init == nil then
    kflag.init = "/sbin/init"
end

os.__kflag = kflag

local pcid = fs.open("/var/pcid", 'w')
pcid.write(os.getComputerLabel())
pcid.close()

local version = fs.open("/proc/version", 'w')
version.write(VERSION)
version.close()

local build = fs.open("/proc/build_date", 'w')
build.write(BUILD_DATE)
build.close()

local sttime = fs.open("/proc/sttime", 'w')
sttime.write(tostring(os.time()))
sttime.close()

DEVICES = {}
MANAGED_FILES = {}
TTYS = {}

os.list_mfiles = {}

os.system_halt = function()
    os.sleep(1000000) --yea...
end

os.viewTable = function (t)
    print(t)
    for k,v in pairs(t) do
        print(k..","..tostring(v))
    end
end

os.runfile = shell.run

os.ferror = function(message)
    term.set_term_color(colors.red)
    print(message)
    term.set_term_color(colors.white)
end

os.safestr = function (s)
    if string.byte(s) > 191 then
        return '@'..string.byte(s)
    end
    return s
end

os.generateSalt = function(l)
    if l < 1 then
        return nil
    end
    local res = ''
    for i = 1, l do
        res = res .. string.char(math.random(32, 126))
    end
    return res
end

if os.loadAPI("/lib/video_manager") then
    print("loaded video")
end

if os.loadAPI("/lib/debug_manager") then
    debug = _G["debug_manager"]
    debug.debug_write("debug: loaded")
else
    debug.debug_write = print
    debug.debug_write("debug: not loaded")
end

if kflag.quiet then
    debug.debug_write = function(x)end
    debug.testcase = function()end
    debug.ferror = function()end
end

os.debug = debug

debug.debug_write("Cubix version "..VERSION.." loading...")

os.lib = {}
os.internals = {}
os.internals._kernel = {}

function loadmodule(nmodule, path)
    os.debug.debug_write('[loadmodule] loading: '..nmodule)
    if os.loadAPI(path) then
        _G[nmodule] = _G[fs.getName(path)]
        if _G[nmodule].libroutine ~= nil then
            _G[nmodule].libroutine()
        else
            os.ferror("[loadmodule] libroutine() not found")
            sleep(1)
        end
        os.lib[nmodule] = _G[fs.getName(path)]
        os.debug.debug_write('[loadmodule] loaded: '..nmodule)
    else
        os.debug.kpanic("[loadmodule] not loaded: "..nmodule)
    end
    --sleep(0.8)
end

os.internals.loadmodule = loadmodule

--acpi module
if kflag.acpi then
    loadmodule("acpi", "/lib/acpi.lua")
end

--filesystem manager
loadmodule("fs_mngr", "/lib/fs_manager")

if fs.exists("/dev/ram") and kflag.acpi then
    os.lib.acpi.acpi_hwake()
else

--process manager
function os.internals._kernel.register_mfile(controller)
    debug.debug_write("[mfile] "..controller.name.." created")
    os.list_mfiles[controller.name] = controller.file
    fs.open(controller.name, 'w', fs.perms.SYS).close()
end

loadmodule("proc", "/lib/proc_manager")

--hash manager
loadmodule("hash", "/lib/hash_manager")

function os.internals._kernel.register_device(d)
    os.debug.debug_write("[device_manager] "..d.name.." created")
    DEVICES[d.name] = d.device
    fs.open(d.name, 'w', fs.perms.SYS).close()
end

--device manager
loadmodule("devices", "/lib/device_manager")
os.list_devices = DEVICES

--tty, login and pipe managers
function os.internals._kernel.register_tty(path, tty)
    os.debug.debug_write("[tty] new tty: "..path)
    TTYS[path] = tty
    fs.open(path, 'w', fs.perms.SYS).close()
end

loadmodule("tty", "/lib/tty_manager")
loadmodule("login", "/lib/login_manager")
loadmodule("pipe", "/lib/pipe_manager")

os.pprint = function(message, pipe, double)
    if double == nil then double = false end
    if message == nil then message = '' end
    if pipe ~= nil then
        pipe:write(message..'\n')
        if double then
            print(message)
        end
    else
        print(message)
    end
end

term.clear()
term.setCursorPos(1,1)

os.__debug_buffer = debug.__debug_buffer

os.__boot_flag = false

os.lib.tty.current_tty("/dev/tty0")

os.lib.login.__CT:generate(3)

os.__parent_init = os.new_process(kflag.init)
os.run_process(os.__parent_init)

os.safe_shutdown()

end
