#!/usr/bin/env lua
--/dev/MAKEDEV: create the basics of unix folder structure in /

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        --print("MAKEDEV: SIGKILL'd!", false)
        return 0
    end
end

function main(args)
    os.runfile("mkdir /proc") --proc_manager
    os.runfile("mkdir /bin") --binaries
    os.runfile("mkdir /sbin") --root binaries
    os.runfile("mkdir /boot") --boot things
    os.runfile("mkdir /etc") --system-wide configuration files and system databases
    os.runfile("mkdir /etc/rc0.d")
    os.runfile("mkdir /etc/rc1.d")
    os.runfile("mkdir /etc/rc2.d")
    os.runfile("mkdir /etc/rc3.d")
    os.runfile("mkdir /etc/rc5.d")
    os.runfile("mkdir /etc/rc6.d")
    os.runfile("mkdir /etc/scripts")
    os.runfile("mkdir /home") --home folder
    os.runfile("mkdir /home/deusa") --default user
    os.runfile("mkdir /lib") --libraries used by /boot/cubix and the binaries
    os.runfile("mkdir /mnt") --mounting (coming soon)
    os.runfile("mkdir /root") --home for root
    os.runfile("mkdir /usr") --user things
    os.runfile("mkdir /usr/bin")
    os.runfile("mkdir /usr/games")
    os.runfile("mkdir /usr/lib")
    os.runfile("mkdir /usr/sbin")
    os.runfile("mkdir /var") --variables
    os.runfile("mkdir /tmp") --temporary, deleted when shutdown
    os.runfile("mkdir /media") --mounting (coming soon)
    os.runfile("mkdir /usr/manuals") --manuals
    print("created all / folders")
end
