#!/usr/bin/env lua
--makeyap: based on pkgdata, creates a .yap file to be a package.
--compatible with Cubix and CraftOS

cwd = ''
YAPI_BIN = '/bin/yapi'

local strsplit = function (inputstr, sep)
    if sep == nil then
        sep = "%s"
    end
    if inputstr == nil then
        return ''
    end
    local t={} ; i=1
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
        t[i] = str
        i = i + 1
    end
    return t
end

local ferror = function(message)
    term.set_term_color(colors.red)
    print(message)
    term.set_term_color(colors.white)
end

local viewTable = function (t)
    print(t)
    for k,v in pairs(t) do
        print(k..","..tostring(v).." ("..type(v)..")")
    end
end

local function extnr(msg)
    term.setTextColor(colors.green)
    write('==> ')
    term.setTextColor(colors.white)
    write(msg..'\n')
end

local function nr(msg)
    term.setTextColor(colors.blue)
    write('  -> ')
    term.setTextColor(colors.white)
    write(msg..'\n')
end

function listAll(p)
    local starting = '/'
    if p ~= nil then
        starting = p
    end
    if starting == '.git' or starting == '/.git' or starting == 'rom' or starting == '/rom' then
        return {folders={}, files={}}
    end
    local folders = {}
    local files = {}
    for _,v in ipairs(fs.list(starting)) do
        local node = fs.combine(starting, v)
        if fs.isDir(node) then
            if not (node == '.git' or node == '/.git' or node == 'rom' or node == '/rom') then
                table.insert(folders, node)
                local cache = listAll(node)
                for _,v in ipairs(cache['folders']) do
                    table.insert(folders, v)
                end
                for _,v in ipairs(cache['files']) do
                    table.insert(files, v)
                end
            end
        else
            table.insert(files, node)
        end
    end
    return {folders=folders, files=files}
end

function parse_pkgdata(lines)
    local pkgobj = {}
    pkgobj['file_assoc'] = {}
    pkgobj['folders'] = {}
    pkgobj['deps'] = {}
    pkgobj['optdep'] = {}
    for k,v in ipairs(lines) do
        if string.sub(v, 1, 1) ~= '#' then --comments
            local d = strsplit(v, '=')
            local p = strsplit(v, ';')
            if d[1] == 'pkgname' then
                pkgobj['name'] = d[2]
            elseif d[1] == 'pkgver' then
                pkgobj['version'] = d[2]
            elseif d[1] == 'pkgbuild' then
                pkgobj['build'] = d[2]
            elseif d[1] == 'author' then
                pkgobj['author'] = d[2]
            elseif d[1] == 'eauthor' then
                pkgobj['email-author'] = d[2]
            elseif d[1] == 'desc' then
                pkgobj['description'] = d[2]
            elseif d[1] == 'url' then
                pkgobj['url'] = d[2]
            elseif d[1] == 'license' then
                pkgobj['license'] = d[2]
            elseif p[1] == 'file' then
                table.insert(pkgobj['file_assoc'], {p[2], p[3]})
            elseif p[1] == 'folder' then
                table.insert(pkgobj['folders'], p[2])
            elseif p[1] == 'optdep' then
                table.insert(pkgobj['optdep'], p[2])
            elseif p[1] == 'dep' then
                table.insert(pkgobj['deps'], p[2])
            elseif d[1] == 'all' then
                pkgobj['SPECIAL_FLAG'] = true
                local nodes = listAll()
                for _,v in ipairs(nodes['folders']) do
                    table.insert(pkgobj['folders'], v)
                end
                for _,v in ipairs(nodes['files']) do
                    table.insert(pkgobj['file_assoc'], {v, v})
                end
            end
        end
    end
    if pkgobj['name'] == nil then
        return ferror("parse_pkgdata: name not found")
    else
        --sanity test
        nr("Package name is "..pkgobj['name'])
    end
    return pkgobj
end

function create_yap(pkgdata, cwd)
    local yapdata = {}
    yapdata['name'] = pkgdata['name']
    yapdata['version'] = pkgdata['version']
    yapdata['build'] = pkgdata['build']
    yapdata['author'] = pkgdata['author']
    yapdata['email_author'] = pkgdata['email-author']
    yapdata['description'] = pkgdata['description']
    yapdata['folders'] = pkgdata['folders']
    yapdata['deps'] = pkgdata['deps']
    yapdata['url'] = pkgdata['url']
    yapdata['license'] = pkgdata['license']
    yapdata['files'] = {}
    yapdata['optdep'] = pkgdata['optdep']
    for k,v in pairs(pkgdata['file_assoc']) do
        local original_file = ''
        if pkgdata['SPECIAL_FLAG'] then
            original_file = v[1]
        else
            original_file = fs.combine(cwd, v[1])
        end
        local absolute_path = v[2]
        yapdata['files'][absolute_path] = ''
        local handler = fs.open(original_file, 'r')
        if handler == nil then
            return ferror("[create_yap] file error: "..original_file)
        end
        local _lines = handler.readAll()
        handler.close()
        local lines = strsplit(_lines, '\n')
        for k,v in ipairs(lines) do
            yapdata['files'][absolute_path] = yapdata['files'][absolute_path] .. v .. '\n'
        end
    end
    return yapdata
end

function write_yapdata(yapdata, path)
    if yapdata['name'] == nil then
        return ferror("[write_yapdata] pkgname is nil")
    end
    if fs.exists(path) then
        return ferror("[write_yapdata] yap target exists")
    end

    local yfile = fs.open(path, 'w')
    yfile.write('name='..yapdata['name']..'\n')
    yfile.write('version='..yapdata['version']..'\n')
    yfile.write('build='..yapdata['build']..'\n')
    yfile.write('author='..yapdata['author']..'\n')
    yfile.write('email-author='..yapdata['email_author']..'\n')
    yfile.write('description='..yapdata['description']..'\n')
    yfile.write("url="..yapdata['url']..'\n')
    yfile.write("license="..yapdata['license']..'\n')

    for k,v in pairs(yapdata['folders']) do
        yfile.write("folder;"..v..'\n')
    end

    for k,v in pairs(yapdata['deps']) do
        yfile.write("depend="..v..'\n')
    end

    for k,v in pairs(yapdata['optdep']) do
        yfile.write("optdepend="..v..'\n')
    end

    for k,v in pairs(yapdata['files']) do
        yfile.write("file;"..k..'\n')
        yfile.write(v)
        yfile.write("END_FILE;\n")
    end

    yfile.close()
    return true --?
end

function main(args)
    cwd = shell.dir()
    --black magic goes here
    local pkgdata_path = fs.combine(cwd, 'pkgdata')
    local handler = nil

    if fs.exists(pkgdata_path) and not fs.isDir(pkgdata_path) then
        handler = fs.open(pkgdata_path, 'r')
    else
        return ferror('makeyap: pkgdata needs to exist')
    end

    if handler == nil then
        return ferror("makeyap: error opening pkgdata")
    end

    local _tLines = handler.readAll()
    handler.close()

    if _tLines == nil then
        return ferror("makeyap: pkgdata is empty")
    end

    local tLines = strsplit(_tLines, '\n')

    extnr("Parsing pkgdata")
    local pkgdata = parse_pkgdata(tLines)
    if not pkgdata then
        return ferror("main: pkgdata == nil")
    end
    nr("Done.")

    extnr("Creating yapdata...")
    local ydata = create_yap(pkgdata, cwd)
    if not ydata then
        return ferror("main: ydata == nil")
    end
    nr("Done.")

    extnr("Writing YAP...")
    local f = ydata['name']..'-'..ydata['build']..'.yap'
    local p = fs.combine(cwd, f)
    if write_yapdata(ydata, p) then
        nr("Done.")
    else
        return ferror("write_yapdata: error")
    end

    extnr("Finished making: "..f)

    if args[1] == '-i' then
        extnr("Installing package with yapi -U")
        os.cshell.run('sudo '..YAPI_BIN.." -U "..p)
        nr("Done.")
    end
end

main({...})
