#!/usr/bin/env lua
--comm_manager: communication and control manager

-- This manager makes communication between processes without files(resolving the /tmp/current_path issue)

local data = {}

function register(process, label, h)
    local runningproc = os.lib.proc.get_processes()[os.getrunning()]
    if h == nil then h = '' end
    if runningproc == nil or runningproc == -1 then
        ferror("comm: no running process")
        return false
    end
    if runningproc.file == process then
        if data[runningproc.file] == nil then
            data[runningproc.file] = {}
        end
        data[runningproc.file][label] = h
    elseif '/'..runningproc.file == process then
        if data['/'..runningproc.file] == nil then
            data['/'..runningproc.file] = {}
        end
        data['/'..runningproc.file][label] = h
    else
        ferror("comm_manager: running process ~= process")
    end
end

function get(process, label)
    if not data[process] then
        return nil
    end
    return data[process][label]
end

function libroutine()
end
