#!/usr/bin/env lua
--device manager
--task: create devices in /dev

--device.name = string
--device.device = table
--device.device.read = function
--device.device.devwrite = function

devices = {}

function loadDevice(name, path)
    os.debug.debug_write("[dmanager] loading "..name)
    if os.loadAPI(path) then
        _G[name] = _G[fs.getName(path)]
        os.debug.debug_write("[dmanager] loaded "..name)
    else
        os.debug.kpanic("[dmanager] not loaded "..name)
    end
end

loadDevice("_dev_random", "/lib/devices/random_device.lua")
loadDevice("_dev_null", "/lib/devices/null_device.lua")
loadDevice("_dev_zero", "/lib/devices/zero_device.lua")

fs.mount = function()
    --TODO: this
end

function libroutine()
    os.internals._kernel.register_device(_dev_random.dev_random)
    os.internals._kernel.register_device(_dev_null.dev_null)
    os.internals._kernel.register_device(_dev_zero.dev_zero)
end

