#!/usr/bin/env lua
--filesystem manager
--task: Manage Filesystems

--TODO: filesystem drivers(vfat, ext3, devfs, tmpfs)

oldfs = deepcopy(fs)

fsdrivers = {}

function load_fs(fsname)
    os.debug.debug_write("[load_fs] loading "..fsname)
    local pth = '/lib/fs/'..fsname..'.lua'
    if os.loadAPI(pth) then
        fsdrivers[fsname] = _G[fs.getName(pth)]
        os.debug.debug_write('[load_fs] loaded: '..fsname)
    else
        os.debug.kpanic("[load_fs] not loaded: "..fsname)
    end
end

function load_filesystems()
    load_fs('cfs') --Cubix File System
    load_fs('tmpfs') --Temporary File System
    --load_fs('ext2')
    --load_fs('ext3')
    --load_fs('ext4')
    --load_fs('vfat')
end

_G["fsdrivers"] = fsdrivers

--yes, this was from uberOS

--local nodes = {} --{ {owner, gid, perms[, linkto]} }
nodes = {}

local mounts = {} --{ {fs, dev}, ... }

fs.perms = {}
fs.perms.ROOT = 1
fs.perms.SYS = 2
fs.perms.NORMAL = 3
fs.perms.FOOL = 4

fs.perm = function (path)
    local perm_obj = {}
    local information = nodes[path]
    perm_obj.writeperm = true
    return perm_obj
end

permission = {}
local __using_perm = nil
local __afterkperm = false

permission.grantAccess = function(perm)
    local _uid = nil
    if not os.__boot_flag then
        if os.lib.login.isSudo() then
            _uid = 0
        else
            _uid = os.lib.login.userUID()
        end
    end
    if (perm == fs.perms.ROOT or perm == fs.perms.SYS) and (_uid == 0 or os.__boot_flag == true) then
        return true
    elseif perm == fs.perms.NORMAL then
        return true
    end
    return false
end

permission.initKernelPerm = function()
    if not __afterkperm then
        __using_perm = fs.perms.SYS
        __afterkperm = true
    end
end

permission.default = function()
    local _uid = os.lib.login.userUID()
    if _uid == 0 then
        __using_perm = fs.perms.ROOT
    elseif _uid > 0 then
        __using_perm = fs.perms.NORMAL
    elseif _uid == -1 then
        __using_perm = fs.perms.FOOL
    end
end

permission.getPerm = function()
    print(__using_perm)
end

fsmanager = {}

fsmanager.normalizePerm = function(perms)
    local tmp = tostring(perms)
    local arr = {}
    for i = 1, 3 do
        local n = tonumber(string.sub(tmp, i, i))
        if n == 0 then arr[i] = "---" end
        if n == 1 then arr[i] = "--x" end
        if n == 2 then arr[i] = "-w-" end
        if n == 3 then arr[i] = "-wx" end
        if n == 4 then arr[i] = "r--" end
        if n == 5 then arr[i] = "r-x" end
        if n == 6 then arr[i] = "rw-" end
        if n == 7 then arr[i] = "rwx" end
    end
    return arr
end

fsmanager.strPerm = function(perms)
    local k = fsmanager.normalizePerm(perms)
    return k[1] .. k[2] .. k[3]
end

fs.verifyPerm = function(path, user, mode)
    local info = fsmanager.getInformation(path)
    local norm = fsmanager.normalizePerm(info.perms)
    if user == info.owner then
        if mode == "r" then return string.sub(norm[1], 1, 1) == "r" end
        if mode == "w" then return string.sub(norm[1], 2, 2) == "w" end
        if mode == "x" then return string.sub(norm[1], 3, 3) == "x" end
    elseif os.lib.login.isInGroup(user, info.gid) then
        if mode == "r" then return string.sub(norm[2], 1, 1) == "r" end
        if mode == "w" then return string.sub(norm[2], 2, 2) == "w" end
        if mode == "x" then return string.sub(norm[2], 3, 3) == "x" end
    else
        if mode == "r" then return string.sub(norm[3], 1, 1) == "r" end
        if mode == "w" then return string.sub(norm[3], 2, 2) == "w" end
        if mode == "x" then return string.sub(norm[3], 3, 3) == "x" end
    end
end

--{owner, owner group, others}
--[[

PERMISSIONS:

---------- 	0000 	no permissions
---x--x--x 	0111 	execute
--w--w--w- 	0222 	write
--wx-wx-wx 	0333 	write & execute
-r--r--r-- 	0444 	read
-r-xr-xr-x 	0555 	read & execute
-rw-rw-rw- 	0666 	read & write
-rwxrwxrwx 	0777 	read, write, & execute

]]
permission.fileCurPerm = function()
    if os.currentUID() == 0 then
        --root here
        return '770'
    elseif os.currentUID() ~= 0 then
        return '777'
    end
end

fsmanager.stripPath = function(base, full)
    if base == full then return '/' end
    return string.sub(full, #base + 1, #full)
end

fsmanager.loadFS = function(mountpath)
    local x = fsdrivers[mounts[mountpath].fs].loadFS
    if x then
        local tmp, r = x(mountpath, mounts[mountpath].dev)
        if not r then return false end
        if mountpath == '/' then mountpath = '' end
        for k,v in pairs(tmp) do
            nodes[mountpath .. k] = v
        end
    end
    return true
end

fsmanager.saveFS = function(mountpath)
    local x = fsdrivers[fsmanager.getMount(mountpath).fs].saveFS
    if x then
        x(mountpath, fsmanager.getMount(mountpath).dev)
    end
end

fsmanager.sync = function()
    os.debug.debug_write('[fsmanager:sync]')
    for k,v in pairs(mounts) do
        os.debug.debug_write('[sync] saveFS: '..k)
        fsmanager.saveFS(k)
    end
end

fsmanager.deleteNode = function(node)
    if not nodes[node] then return true end
    if fs.verifyPerm(node, os.currentUID(), 'w') then
    --if fs.perm(node).writeperm then
        nodes[node] = nil
        return true
    else
        os.ferror("fsmanager.deleteNode: Access Denied")
    end
    return false
end

fsmanager.getInformation = function(node)
    local p = node
    if node == '/' then
        return {owner = 0, perms = '755', gid = 0}
    end
    if nodes[p] then
        return deepcopy(nodes[p])
    end
    return {owner = 0, perms = '777', gid = 0}
end

fsmanager.setNode = function(node, owner, perms, linkto, gid)
    if node == '/' then
        nodes['/'] = {owner = 0, perms = '755', gid = 0}
        return true
    end
    if not nodes[node] then
        --create node
        if fs.verifyPerm(node, os.currentUID(), 'w') then
            nodes[node] = deepcopy(fsmanager.getInformation(node))
        else
            os.ferror("fsmanager.setNode [perm]: Access denied")
            return false
        end
    end
    owner = owner or nodes[node].owner
    perms = perms or nodes[node].perms
    gid = gid or nodes[node].gid
    perms = tonumber(perms)
    if nodes[node].owner == os.currentUID() then
        nodes[node].owner = owner
        nodes[node].gid = gid
        nodes[node].perms = perms
        nodes[node].linkto = linkto
    else
        os.ferror("fsmanager.setNode [uid]: Access denied")
        return false
    end
end

fsmanager.viewNodes = function()
    os.viewTable(nodes)
end

fsmanager.canMount = function(fs)
    if os.__boot_flag then
        return true
    else
        return fsdrivers[fs].canMount(os.currentUID())
    end
end

fsmanager.mount = function(device, filesystem, path)
    --if not permission.grantAccess(fs.perms.SYS) then
    --    os.ferror("mount: system permission is required to mount")
    --    return false
    --end
    if not fsmanager.canMount(filesystem) then
        os.ferror("mount: current user can't mount "..filesystem)
        return false
    end
    if not fsdrivers[filesystem] then
        os.ferror("mount: can't mount "..device..": filesystem not loaded")
        return false
    end
    if mounts[path] then
        os.ferror("mount: filesystem already mounted")
        return false
    end
    if not oldfs.exists(path) then
        ferror("mount: mountpath "..path.." doesn't exist")
        return false
    end
    if not oldfs.isDir(path) then
        ferror("mount: mountpath is not a folder")
        return false
    end
    os.debug.debug_write("[mount] mounting "..device..": "..filesystem.." at "..path, false)
    mounts[path] = {["fs"] = filesystem, ["dev"] = device}
    local r = fsmanager.loadFS(path, device)
    if not r then
        mounts[path] = nil
        os.ferror("mount: unable to mount")
        return false
    end
    return true
end

fsmanager.umount_path = function(mpath)
    if not permission.grantAccess(fs.perms.SYS) then
        --os.ferror("umount: system permission is required to umount")
        return {false, 'system permission is required to umount'}
    end
    if mpath == '/' then
        return {false, "device is busy"}
    end
    if mounts[mpath] then
        fsmanager.saveFS(mpath)
        mounts[mpath] = nil
        return {true}
    end
    return {false, 'mountpath not found'}
end

fsmanager.umount_dev = function(dev)
    if not permission.grantAccess(fs.perms.SYS) then
        --os.ferror("umount: system permission is required to umount")
        return {false, 'system permission is required to umount'}
    end
    if dev == '/dev/hdd' then
        return {false, "device is busy"}
    end
    local k = next(mounts)
    while k do
        if mounts[k] then
            if mounts[k]['dev'] == dev then
                fsmanager.saveFS(k)
                mounts[k] = nil
                return {true}
            end
        end
        k = next(mounts)
    end
    return {false, 'device not found'}
end

fsmanager.getMount = function(mountpath)
    return deepcopy(mounts[mountpath])
end

fsmanager.getMounts = function()
    return deepcopy(mounts)
end

fsmanager._test = function()
    fsmanager.setNode("/startup", 0, 755, nil, 0)
end

function shutdown_procedure()
    local k = next(mounts)
    while k do
        if mounts[k] then
            os.debug.debug_write('[fs_mngr] umounting '..mounts[k]['dev']..' at '..k)
            fsmanager.saveFS(k)
            mounts[k] = nil
            --return {true}
        end
        k = next(mounts)
    end
    sleep(.5)
end


-- how to basic: fs.complete
-- fs.find
-- fs.getDir

fs.combine = oldfs.combine

fs.getSize = function (path)
    for k,v in pairs(mounts) do
        if string.sub(path, 1, #k) == k and k ~= '/' then
            --mounted path ahead
            return fsdrivers[mounts[k]['fs']].getSize(k, string.sub(path, #k + 1))
        end
    end
    --normal path
    if fsdrivers['cfs'] then
        return fsdrivers['cfs'].getSize('/', path)
    else
        return oldfs.getSize(path)
    end
end

fs.getFreeSpace = oldfs.getFreeSpace

fs.getDrive = oldfs.getDrive --???

fs.getDir = oldfs.getDir

fs.exists = function(path)
    for k,v in pairs(mounts) do
        if string.sub(path, 1, #k) == k and k ~= '/' then
            --mounted path ahead
            return fsdrivers[mounts[k]['fs']].exists(k, string.sub(path, #k + 2))
        end
    end
    --normal path(as cfs mounted in '/')
    if fsdrivers['cfs'] then
        return fsdrivers['cfs'].exists('/', path)
    else
        return oldfs.exists(path)
    end
end

fs.move = function(fpath, tpath)
    return oldfs.move(fpath, tpath)
end

fs.copy = function(fpath, tpath)
    return oldfs.copy(fpath, tpath)
end

fs.delete = function(path)
    for k,v in pairs(mounts) do
        if string.sub(path, 1, #k) == k and k ~= '/' then
            --mounted path ahead
            return fsdrivers[mounts[k]['fs']].delete(k, string.sub(path, #k + 2))
        end
    end
    --normal path(as cfs mounted in '/')
    if fsdrivers['cfs'] then
        return fsdrivers['cfs'].delete('/', path)
    else
        return oldfs.delete(path)
    end
end

fs.isReadOnly = oldfs.isReadOnly

fs.list = function(path)
    for k,v in pairs(mounts) do
        if string.sub(path, 1, #k) == k and k ~= '/' then
            --mounted path ahead
            return fsdrivers[mounts[k]['fs']].list(k, string.sub(path, #k + 1))
        end
    end
    --normal path(as cfs mounted in '/')
    if fsdrivers['cfs'] then
        return fsdrivers['cfs'].list('/', path)
    else
        return oldfs.list(path)
    end
end


fs.makeDir = function(path)
    for k,v in pairs(mounts) do
        if string.sub(path, 1, #k) == k and k ~= '/' then
            --mounted path ahead
            return fsdrivers[mounts[k]['fs']].makeDir(k, string.sub(path, #k + 2))
        end
    end
    --normal path(as cfs mounted in '/')
    if fsdrivers['cfs'] then
        return fsdrivers['cfs'].makeDir('/', path)
    else
        return oldfs.makeDir(path)
    end
end

fs.isDir = function(path)
    for k,v in pairs(mounts) do
        if string.sub(path, 1, #k) == k and k ~= '/' then
            --mounted path ahead
            return fsdrivers[mounts[k]['fs']].isDir(k, string.sub(path, #k + 2))
        end
    end
    --normal path(as cfs mounted in '/')
    if fsdrivers['cfs'] then
        return fsdrivers['cfs'].isDir('/', path)
    else
        return oldfs.isDir(path)
    end
end

fs.open = function (path, mode, perm)
    for k,v in pairs(mounts) do
        if string.sub(path, 1, #k) == k and k ~= '/' then
            --mounted path ahead
            return fsdrivers[mounts[k]['fs']].open(k, string.sub(path, #k + 2), mode)
        end
    end
    --normal path
    if fsdrivers['cfs'] then
        return fsdrivers['cfs'].open('/', path, mode)
    else
        return oldfs.open(path, mode)
    end
end

function run_fstab()
    os.debug.debug_write("[run_fstab] reading fstab")
    if not fs.exists("/etc/fstab") then
        os.debug.kpanic("/etc/fstab not found")
    end
    local h = fs.open("/etc/fstab", 'r')
    local _fstab = h.readAll()
    h.close()
    local lines = os.strsplit(_fstab, '\n')
    for k,v in ipairs(lines) do
        local spl = os.strsplit(v, ';')
        local device = spl[1]
        local mpoint = spl[2]
        local fs = spl[3]
        local options = spl[4]
        fsmanager.mount(device, fs, mpoint)
    end
end

function libroutine()
    --os.deepcopy = deepcopy
    _G["permission"] = permission
    _G["fsmanager"] = fsmanager
    _G['oldfs'] = oldfs
    load_filesystems()
    run_fstab()
end
