#!/usr/bin/env lua
--/sbin/adduser: adding new users to cubix

_handler = {}
_handler.signal_handler = function(sig)
    if sig == 'kill' then
        --print("adduser: SIGKILL")
        return 0
    end
end

function main(args)
    if #args == 0 then
        print("usage: adduser <user> <password>")
        return 0
    end
    local nu, np = args[1], args[2]
    if nu == 'root' then
        os.ferror("you cannot create a new root user")
    end
    if os.lib.login.add_new_user(nu, np) then
        print("created "..nu)
    else
        os.ferror("adduser: error creating new user")
    end
end

main({...})
