#!/usr/bin/env lua
--/sbin/init: manages (stuff of) the user space

local RUNLEVELFUNC = {}

function run_scripts(runlevel)
    local runlevel_folder = rprintf("/etc/cinit.d/rc%d.d", runlevel)

    for _,filepath in pairs(fs.list(runlevel_folder)) do
        local src_path = runlevel_folder .. '/' .. filepath
        --TODO: Add shel ability to parse shebangs
        execv('/bin/cshell.new', {src_path})
    end
end

function main(args)
    if lib.pm.currentuid() ~= 0 then
        ferror("init: only superuser can run init")
        return 1
    end

    syslog.serlog(syslog.S_INFO, "init", "start")

    if args[1] ~= nil then
        runlevel = tonumber(args[1])
    else
        if fs.exists("/etc/inittab") then
            local inittab_data = fs_readall("/etc/inittab")
            if not inittab_data then
                syslog.panic("inittab", "error reading inittab")
            end
            local r = string.split(inittab_data, ':')[2]
            runlevel = tonumber(r)
        else
            syslog.panic("init", "/etc/inittab not found")
        end
    end

    if lib.tty then
        lib.tty.current_tty("/dev/tty1")
    end

    if runlevel == 0 then
        os.shutdown()
    end

    if runlevel == 6 then
        os.reboot()
    end

    -- run init scripts
    run_scripts(runlevel)
    return 0
end

main({...})
