#!/usr/bin/env lua
--/sbin/init: manages (stuff of) the user space

local RUNLEVELFUNC = {}

function run_scripts(runlevel)
    local runlevel_folder = rprintf("/etc/cinit.d/rc%d.d", runlevel)

    for _,filepath in pairs(fs.list(runlevel_folder)) do
        local src_path = runlevel_folder .. '/' .. filepath
        execv('/bin/cshell.new', {src_path})
    end
end

function main(args)
    if lib.pm.currentuid() ~= 0 then
        syslog.panic('init', 'only superuser can run init')
    end

    syslog.serlog(syslog.S_INFO, "init", "/sbin/init: start")

    if args[1] ~= nil then
        runlevel = tonumber(args[1])
    else
        if fs.exists("/etc/inittab") then
            local r = string.split(fs_readall("/etc/inittab"), ':')[2]
            runlevel = tonumber(r)
        else
            syslog.panic("init", "/etc/inittab not found")
            return 1
        end
    end

    if lib.tty then
        lib.tty.current_tty("/dev/tty1")
    end

    if runlevel == 0 then
        os.shutdown()
    end

    if runlevel == 6 then
        os.reboot()
    end

    run_scripts(runlevel)
    -- RUNLEVELFUNC[runlevel]()
    return 0
end

main({...})
