#!/usr/bin/env lua
--/sbin/cubix-installer: cubix installator for CraftOS

function download_file(url)
    http.request(url)
    local req = true
    while req do
        local e, url, stext = os.pullEvent()
        if e == 'http_success' then
            local rText = stext.readAll()
            stext.close()
            return rText
        elseif e == 'http_failure' then
            req = false
            return {false, 'http_failure'}
        end
    end
end

function _prompt(message, yes, nope)
    write(message..'['..yes..'/'..nope..'] ')
    local result = read()
    if result == yes then
        return true
    else
        return false
    end
end

term.set_term_color = function (c)
    if term.isColor() then
        term.setTextColor(c)
    end
end

function warning(msg)
    term.set_term_color(colors.yellow)
    print(msg)
    term.set_term_color(colors.white)
end

function format_all()
    for k,v in pairs(fs.list('/'))do
        if v ~= 'rom' then
            fs.delete(v)
        end
    end
end

if IS_CUBIX ~= nil and IS_CUBIX == true then
    if prompt("Do you want to reinstall cubix?", "Y", "n") then
        print("reinstall")
    end
else
    --Running CraftOS
    warning("WARNING: Installing cubix will wipe out the current computer")
    if _prompt("Do you want to continue the installation?", "Y", "n") then
    else
        return 0
    end
    print("==> [cubix_installer] formatting disk")
    format_all()
    print("==> [cubix_installer] downloading and installing cubix at disk")
    shell.run("pastebin run W5ZkVYSi lkmnds cubix")
    shell.run("FINISHINSTALL")
    write("")
    print("Cubix installed!")
    os.sleep(1)
    os.reboot()
end

