#!/usr/bin/env lua
--/sbin/init: manages (some part of) the user space

--well, for now its just a placeholder for being a parent of all processes

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        print("init: recieved SIGKILL")
        os.runfile("/sbin/shutdown")
    end
end

return 0
