#!/usr/bin/env lua
--/bin/kill: kills processes

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        os.debug.debug_write("kill: recieved SIGKILL", false)
        return 0
    end
end

function main(args)
    if #args == 1 then
        local pid = args[1]
        local p = os.processes[tonumber(pid)]
        os.send_signal(p, os.signals.SIGKILL)
    elseif #args > 1 then
        for k,v in pairs(args) do
            local proc = os.processes[tonumber(v)]
            os.send_signal(proc, os.signals.SIGKILL)
        end
    else
        print("usage: kill <pid1> <pid2> <pid3> ...")
    end
end
