#!/usr/bin/env lua
--/bin/kill: kills processes

function main(args)
    if #args == 1 then
        local pid = args[1]
        local p = os.lib.proc.get_by_pid(tonumber(pid))
        os.send_signal(p, os.signals.SIGKILL)
    elseif #args > 1 then
        for k,v in pairs(args) do
            local proc = os.lib.proc.get_by_pid(v)
            os.send_signal(proc, os.signals.SIGKILL)
        end
    else
        print("usage: kill <pid1> <pid2> <pid3> ...")
    end
end

main({...})
