#!/usr/bin/env lua
--/bin/kill: kills processes

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        os.debug.debug_write("kill: recieved SIGKILL", false)
        return 0
    end
end

function main(args)
    local pid = args[1]
    p = os.processes[tonumber(pid)]
    os.send_signal(p, os.signals.SIGKILL)
end
