#!/usr/bin/env lua
--/bin/login: login user to its shell access

local user = ...
if user == nil then user = "^" end

local PC_LABEL = fs.open("/var/pcid", 'r').readAll()

if os.loadAPI("/lib/login_manager") then
    loginmngr = _G["login_manager"]
else
    print("cannot load login_manager")
    exit()
end

term.clear()
term.setCursorPos(1,1)

local try_user = ""
local try_pwd = ""

if user == "^" then
    write("\n"..PC_LABEL.." login: ")
    try_user = read()
    write("\nPassword: ")
    try_pwd = read("")
else
    try_user = user
    write("user: "..try_user.."\n")
    write("\nPassword: ")
    try_pwd = read("")
end

if loginmngr.login(try_user, try_pwd) then
    print("logged")
    local k = fs.open("/tmp/current_user", 'w') k.write(try_user) k.close()
    local k2 = fs.open("/tmp/current_path", 'w') k2.write("/home/"..try_user) k2.close()
    shell.run("/bin/shell")
else
    print("erroneus user or password.")
end


