#!/usr/bin/env lua
--/bin/login: login user to its shell access

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        print("login: recieved SIGKILL")
        return 0
    end
end

if os.loadAPI("/lib/login_manager") then
    loginmngr = _G["login_manager"]
else
    print("cannot load login_manager")
    exit()
end

function main(args)
    local user = args[1]
    if user == nil then user = "^" end
    local PC_LABEL = fs.open("/var/pcid", 'r').readAll()
    local try_user = ""
    local try_pwd = ""

    if user == "^" then
        write(PC_LABEL.." login: ")
        try_user = read()
        write("\nPassword: ")
        try_pwd = read("")
    else
        try_user = user
        write("\nPassword: ")
        try_pwd = read("")
    end

    if loginmngr.login(try_user, try_pwd) then
        local k = fs.open("/tmp/current_user", 'w') k.write(try_user) k.close()
        local k2 = fs.open("/tmp/current_path", 'w')
        if try_user ~= 'root' then
            k2.write("/home/"..try_user)
        else
            k2.write("/root")
        end
        k2.close()
        os.runfile_proc("/bin/cshell")
    else
        print("erroneus user or password.")
    end
end

