#!/usr/bin/env lua
--/bin/modprobe: load/reload cubix libraries

function usage()
    print("use: modprobe <module name> <path to module>")
end

function main(args)
    if #args ~= 2 then
        usage()
        return 0
    end
    local alias, path = args[1], shell.resolve(args[2])
    os.internals.loadmodule(alias, path)
end

main({...})
