#!/usr/bin/env lua
--/bin/modprobe: load/reload cubix libraries

function usage()
    print("use: modprobe <module name> <path to module>")
end

function main(args)
    if #args ~= 2 then
        usage()
        return 0
    end
    if lib.pm.currentuid() ~= 0 then
        return ferror("only root can use modprobe")
    end
    local alias, path = args[1], fs_resolve(args[2])
    if not path then
        cubix.load(alias, cubix.get_path(alias))
    else
        cubix.load(alias, path)
    end
end

main({...})
