#!/usr/bin/env lua
--/bin/hibernate: wrapper to (acpi) hibernate

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        print("pm-hibernate: recieved SIGKILL")
        return 0
    end
end

function main(args)
    os.hibernate()
end
