#!/usr/bin/env lua
--/bin/pm-suspend: wrapper to ACPI suspend function

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        os.debug.debug_write("pm-suspend: recieved SIGKILL", false)
        return 0
    end
end

function main(args)
    os.suspend()
    return 0
end
