#!/usr/bin/env lua
--/bin/reboot: wrapper to CC reboot

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        print("reboot: recieved SIGKILL")
        return 0
    end
end

function main(args)
    os.reboot()
end

main({...})
