#!/usr/bin/env lua
--/bin/reboot: wrapper to CC reboot

function main(args)
    os.debug.debug_write("[reboot] rebooting...")
    os.debug.debug_write("deleting temporary")

    os.runfile("rm /tmp")
    os.runfile("mkdir /tmp")

    os.sleep(1)
    os.reboot()
end
