#!/usr/bin/env lua
--/bin/sbl-mkconfig: make systems.cfg

function main(args)
    if #args == 0 then
        print("welcome to sbl-mkconfig!")
        print("here you can write a new systems.cfg file from scratch")
        local entries = {}
        while true do
            write("OS entry: ")
            local osentry = read()
            if osentry == '' then break end
            write("OS script: ")
            local oscmd = read()
            entries[osentry] = oscmd
        end
        print("writing to /boot/sblcfg/systems.cfg")
        if entries[''] == '' then
            local sResult = ''
            for k,v in pairs(entries) do
                sResult = sResult .. k .. ';' .. v .. '\n'
            end
            local h = oldfs.open("/boot/sblcfg/systems.cfg", 'w')
            h.write(sResult)
            h.close()
        else
            print("sbl-mkconfig: aborted.")
        end
        print("sbl-mkconfig: done!")
    elseif #args == 1 then
        local mode = args[1]
        if mode == 'default' then
            print("sbl-mkconfig: restoring system.cfg to default.cfg")
            local default = fs.open("/boot/sblcfg/default.cfg", 'r')
            local systems = fs.open("/boot/sblcfg/systems.cfg", 'w')
            systems.write(default.readAll())
            default.close()
            systems.close()
            print("Done!")
        end
    else
        print("usage: sbl-mkconfig [mode]")
    end
end

main({...})
