#!/usr/bin/env lua
--/sbin/reboot: wrapper to CC shutdown

debug = {}
debug.debug_write = print

function main()
    debug.debug_write("[shutdown] turning off...")
    debug.debug_write("deleting temporary")

    os.runfile("rm /tmp")
    os.runfile("mkdir /tmp")

    debug.debug_write("[shutdown] sending HALT.")
    os.sleep(1)
    os.shutdown()
end
