#!/usr/bin/env lua
--/sbin/reboot: wrapper to CC shutdown

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        print("shutdown: recieved SIGKILL")
        return 0
    end
end

function main(args)
    os.runfile_proc("/sbin/init" , {"0"})
end
