#!/usr/bin/env lua
--bootsplash

_handler = {}
_handler.signal_handler = function (sig)
    if sig == 'kill' then
        os.debug.debug_write("bootsplashd: SIGKILL'd!", false)
        return 0
    end
end

AUTHOR = "Lukas Mendes"
VERSION = '0.0.1'

function main(args)
    if args[1] == 'set-theme' then
        local theme = args[2]
        if theme == 'text' then
            local h = fs.open("/etc/bootsplash.default", 'w')
            h.write('text')
            h.close()
        elseif fs.exists("/usr/lib/bootsplash/"..theme..'.theme') then
            ferror("Still coming...")
        else
            ferror("theme not found")
            return 0
        end
    else
        print("usage: bootsplash <mode>")
    end
end
